# -*- coding: utf-8 -*-
"""space_explorer_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fws-G0qAZcnKP6oO0GZwDZwHycJ1iWzt
"""

!pip install requests

import requests
import random

# Function to fetch Astronomy Picture of the Day (APOD)
def get_apod():
    url = "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        return {
            "title": data.get("title"),
            "url": data.get("url"),
            "description": data.get("explanation")
        }
    else:
        return None

# Function to fetch Mars Weather
def get_mars_weather():
    url = "https://api.maas2.apollorion.com/"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        return {
            "sol": data.get("sol"),
            "temperature": data.get("atmo_opacity"),
            "pressure": data.get("pressure"),
            "season": data.get("season")
        }
    else:
        return None

# List of random space facts
space_facts = [
    "A day on Venus is longer than a year on Venus!",
    "One million Earths could fit inside the Sun.",
    "The Moon is drifting away from Earth at a rate of 3.8 cm per year.",
    "Mars has the largest volcano in the solar system: Olympus Mons.",
    "Jupiter has 79 known moons as of now!"
]

# Function to get a random space fact
def get_space_fact():
    return random.choice(space_facts)

# Space Explorer Chatbot
def space_explorer_bot():
    print("Hello! I'm Space Explorer Bot. Ask me anything about space!")
    print("Options: 'APOD', 'Mars weather', 'Random fact', or 'Exit'\n")

    while True:
        user_input = input("You: ").lower()
        if user_input == "exit":
            print("Goodbye! Keep exploring the universe! 🚀")
            break
        elif user_input == "apod":
            apod = get_apod()
            if apod:
                print(f"\nTitle: {apod['title']}")
                print(f"Image URL: {apod['url']}")
                print(f"Description: {apod['description']}\n")
            else:
                print("Sorry, I couldn't fetch today's APOD. Try again later!")
        elif user_input == "mars weather":
            mars_weather = get_mars_weather()
            if mars_weather:
                print(f"\nMars Weather Report (Sol {mars_weather['sol']}):")
                print(f"Temperature: {mars_weather['temperature']}")
                print(f"Pressure: {mars_weather['pressure']}")
                print(f"Season: {mars_weather['season']}\n")
            else:
                print("Sorry, I couldn't fetch Mars weather. Try again later!")
        elif user_input == "random fact":
            print(f"\nDid you know? {get_space_fact()}\n")
        else:
            print("I didn't understand that. Try 'APOD', 'Mars weather', 'Random fact', or 'Exit'.")

# Start the chatbot
space_explorer_bot()